"""
===============================================================================
Module: ownership_models.py

Purpose:
    Defines all ownership domain models used by the Ownership Intelligence
    Engine.

Responsibilities:
    - Ownership data models
    - Promoter models
    - Institutional ownership models
    - Ownership scoring models
    - Ownership reporting models

Author:
    EIOS (Everest Investment Operating System)
===============================================================================
"""

from dataclasses import dataclass, field
from datetime import date
from typing import List, Optional


# =============================================================================
# Quarterly Ownership Snapshot
# =============================================================================

@dataclass
class OwnershipQuarter:
    """
    Represents one quarterly shareholding pattern.
    """

    financial_year: str
    quarter: str

    promoter_percent: float = 0.0
    fii_percent: float = 0.0
    dii_percent: float = 0.0
    public_percent: float = 0.0
    other_percent: float = 0.0

    pledged_percent: float = 0.0


# =============================================================================
# Promoter Holding
# =============================================================================

@dataclass
class PromoterHolding:
    """
    Promoter ownership assessment.
    """

    current_percent: float = 0.0
    previous_percent: float = 0.0

    yearly_change: float = 0.0

    pledged_percent: float = 0.0

    buying: float = 0.0
    selling: float = 0.0

    confidence: str = "UNKNOWN"


# =============================================================================
# FII Holding
# =============================================================================

@dataclass
class FIIHolding:
    """
    Foreign Institutional Investor ownership.
    """

    current_percent: float = 0.0
    previous_percent: float = 0.0

    quarterly_change: float = 0.0
    yearly_change: float = 0.0

    institution_count: int = 0

    trend: str = "UNKNOWN"


# =============================================================================
# DII Holding
# =============================================================================

@dataclass
class DIIHolding:
    """
    Domestic Institutional Investor ownership.
    """

    current_percent: float = 0.0
    previous_percent: float = 0.0

    quarterly_change: float = 0.0
    yearly_change: float = 0.0

    mutual_fund_percent: float = 0.0
    insurance_percent: float = 0.0

    trend: str = "UNKNOWN"


# =============================================================================
# Insider Activity
# =============================================================================

@dataclass
class InsiderActivity:
    """
    Insider buying / selling information.
    """

    buying_value: float = 0.0
    selling_value: float = 0.0

    net_activity: float = 0.0

    last_transaction_date: Optional[date] = None


# =============================================================================
# Ownership Trend
# =============================================================================

@dataclass
class OwnershipTrend:
    """
    Long-term ownership trend.
    """

    direction: str = "UNKNOWN"

    duration_quarters: int = 0

    confidence: str = "UNKNOWN"

    summary: str = ""


# =============================================================================
# Ownership Score
# =============================================================================

@dataclass
class OwnershipScore:
    """
    Ownership Intelligence score.
    """

    promoter_score: float = 0.0
    fii_score: float = 0.0
    dii_score: float = 0.0

    insider_score: float = 0.0
    concentration_score: float = 0.0

    total_score: float = 0.0


# =============================================================================
# Ownership Assessment
# =============================================================================

@dataclass
class OwnershipAssessment:
    """
    Ownership reasoning generated by the engine.
    """

    strengths: List[str] = field(default_factory=list)

    weaknesses: List[str] = field(default_factory=list)

    risks: List[str] = field(default_factory=list)

    opportunities: List[str] = field(default_factory=list)

    confidence: str = "UNKNOWN"

    recommendation: str = "WATCH"


# =============================================================================
# Ownership Report
# =============================================================================

@dataclass
class OwnershipReport:
    """
    Final report produced by Ownership Intelligence Engine.
    """

    company_name: str = ""

    generated_on: Optional[date] = None

    ownership_score: Optional[OwnershipScore] = None

    assessment: Optional[OwnershipAssessment] = None

    summary: str = ""