from .knowledge import Knowledge


class KnowledgeRegistry:
    """
    Stores all knowledge objects generated by EIOS.
    """

    def __init__(self):
        self._knowledge = []

    def add(self, knowledge: Knowledge):
        """
        Add knowledge to registry.
        """
        self._knowledge.append(knowledge)

    def all(self):
        """
        Return all knowledge.
        """
        return self._knowledge

    def count(self):
        """
        Total knowledge objects.
        """
        return len(self._knowledge)

    def clear(self):
        """
        Remove all knowledge.
        """
        self._knowledge.clear()

    def show_knowledge(self):
        """
        Display all knowledge.
        """
        print()
        print("=" * 60)
        print("KNOWLEDGE")
        print("=" * 60)

        if not self._knowledge:
            print("No knowledge available.")
            return

        for item in self._knowledge:
            print(item.summary())

        print()
        print(f"Total Knowledge : {self.count()}")