"""
===============================================================================
EIOS
Everest Investment Operating System

Decision Section

Stores the final investment decision generated by
the Decision Office.

Release:
    Sprint 7
===============================================================================
"""

from dataclasses import dataclass

from .base_section import BaseSection


@dataclass
class DecisionSection(BaseSection):
    """
    Stores the final investment decision.
    """

    recommendation: str = ""
    confidence: float = 0.0
    summary: str = ""
    target_weight: float = 0.0