from typing import List

from .intelligence import Intelligence


class IntelligenceMesh:
    """
    Central repository for all intelligence generated by EIOS.
    """

    def __init__(self):
        self._intelligence: List[Intelligence] = []

    def publish(self, intelligence: Intelligence):
        """Store a new intelligence object."""
        self._intelligence.append(intelligence)

    def get_all(self) -> List[Intelligence]:
        """Return all published intelligence."""
        return list(self._intelligence)

    def count(self) -> int:
        """Return number of intelligence objects."""
        return len(self._intelligence)

    def clear(self):
        """Remove all intelligence."""
        self._intelligence.clear()