"""
EIOS
Everest Investment Operating System

Volume Growth Catalyst Patterns

Purpose:
    Canonical catalyst patterns belonging to the
    VOLUME_GROWTH catalyst family.

Design:
    Passive data definitions only.

    No scoring.
    No ranking.
    No valuation.
    No investment decision.

Pattern Boundary:
    These patterns describe identifiable mechanisms through
    which physical, transactional, or usage volume can
    accelerate.

    They do not replace more specific catalyst families such as:

        - Revenue Growth
        - Pricing
        - Customer Addition
        - Market Share
        - Capacity Expansion
        - Product Mix
"""


from typing import List


from modules.opportunity.catalyst.catalyst_patterns import (
    CatalystPattern,
)


from modules.opportunity.catalyst.catalyst_taxonomy import (
    CatalystFamily,
)


# ==========================================================
# VOLUME GROWTH CATALYST PATTERNS
# ==========================================================


VOLUME_PATTERNS: List[CatalystPattern] = [

    # ======================================================
    # 1. ORGANIC VOLUME ACCELERATION
    # ======================================================

    CatalystPattern(
        pattern_id="PAT-VOLUME-ORGANIC-ACCELERATION",
        family=CatalystFamily.VOLUME_GROWTH,
        name="Organic Volume Acceleration",

        description=(
            "A measurable acceleration in physical or "
            "transactional volume generated by the existing "
            "business without a new capacity project being "
            "the primary catalyst."
        ),

        trigger_signals=[
            "volume growth acceleration",
            "unit growth acceleration",
            "shipment growth",
            "production volume growth",
            "transaction volume acceleration",
        ],

        mechanism=(
            "Underlying demand or business activity increases "
            "the number of units, transactions, shipments, or "
            "other measurable physical outputs generated by "
            "the existing operating base."
        ),

        transmission_channels=[
            "Units",
            "Shipments",
            "Transactions",
            "Revenue",
            "Operating Leverage",
        ],

        leading_indicators=[
            "Monthly unit volumes",
            "Shipment trends",
            "Transaction counts",
            "Customer order frequency",
            "Production throughput",
        ],

        confirmation_indicators=[
            "Sequential volume acceleration",
            "Year-on-year volume growth",
            "Higher shipment volumes",
            "Higher transaction volumes",
            "Sustained throughput growth",
        ],

        typical_time_horizon="2-12 quarters",

        earnings_channels=[
            "Revenue",
            "EBITDA",
            "EPS",
            "FCF",
        ],

        market_mistake=(
            "The market focuses on historical volume growth "
            "and fails to recognize an underlying acceleration "
            "in the physical or transactional demand trajectory."
        ),

        second_order_effects=[
            "Operating leverage",
            "Higher asset utilisation",
            "Improved return on capital",
            "Stronger customer relationships",
        ],

        disconfirming_evidence=[
            "Volume deceleration",
            "Weakening order activity",
            "Shipment decline",
            "Customer demand deterioration",
        ],

        kill_switch=(
            "Forward volume indicators fail to confirm "
            "the expected acceleration in underlying "
            "physical or transactional demand."
        ),
    ),


    # ======================================================
    # 2. END-MARKET VOLUME EXPANSION
    # ======================================================

    CatalystPattern(
        pattern_id="PAT-VOLUME-END-MARKET-EXPANSION",
        family=CatalystFamily.VOLUME_GROWTH,
        name="End-Market Volume Expansion",

        description=(
            "Expansion in the underlying physical or "
            "transactional volume of an addressable end market "
            "creates incremental volume growth for the company."
        ),

        trigger_signals=[
            "end-market volume growth",
            "industry volume expansion",
            "market unit growth",
            "industry throughput growth",
            "sector demand acceleration",
        ],

        mechanism=(
            "Growth in the underlying industry volume increases "
            "the number of units or transactions available to "
            "participating companies."
        ),

        transmission_channels=[
            "Industry Volume",
            "Units",
            "Market Demand",
            "Revenue",
            "Market Share",
        ],

        leading_indicators=[
            "Industry shipment data",
            "Industry production data",
            "Sector transaction volumes",
            "Vehicle or equipment registrations",
            "Industry utilisation trends",
        ],

        confirmation_indicators=[
            "Industry volume growth",
            "Company volume growth",
            "Higher industry throughput",
            "Improved company shipment trends",
            "Sustained end-market expansion",
        ],

        typical_time_horizon="4-24 months",

        earnings_channels=[
            "Revenue",
            "EBITDA",
            "EPS",
            "FCF",
        ],

        market_mistake=(
            "The market assumes the company's growth is "
            "dependent only on market share gains and "
            "underestimates the contribution from expanding "
            "underlying end-market volume."
        ),

        second_order_effects=[
            "Operating leverage",
            "Higher capacity utilisation",
            "Supplier volume growth",
            "Improved return on capital",
        ],

        disconfirming_evidence=[
            "End-market contraction",
            "Industry volume stagnation",
            "Demand deterioration",
            "Company volume failing to participate",
        ],

        kill_switch=(
            "Underlying end-market volume fails to expand "
            "or the company fails to participate in the "
            "industry volume growth."
        ),
    ),


    # ======================================================
    # 3. CUSTOMER USAGE INTENSIFICATION
    # ======================================================

    CatalystPattern(
        pattern_id="PAT-VOLUME-USAGE-INTENSIFICATION",
        family=CatalystFamily.VOLUME_GROWTH,
        name="Customer Usage Intensification",

        description=(
            "Existing customers increase the frequency or "
            "quantity of product or service usage, generating "
            "higher transactional or physical volume."
        ),

        trigger_signals=[
            "usage growth",
            "higher consumption",
            "transaction frequency increase",
            "usage intensity increase",
            "higher units per customer",
        ],

        mechanism=(
            "Existing customers consume more units or use the "
            "service more frequently, increasing volume without "
            "requiring equivalent customer additions."
        ),

        transmission_channels=[
            "Usage",
            "Transactions",
            "Units per Customer",
            "Revenue",
            "Customer Lifetime Value",
        ],

        leading_indicators=[
            "Usage frequency",
            "Units per customer",
            "Transactions per customer",
            "Consumption trends",
            "Active customer utilisation",
        ],

        confirmation_indicators=[
            "Higher usage per customer",
            "Higher transaction frequency",
            "Higher consumption volume",
            "Sustained unit growth per customer",
        ],

        typical_time_horizon="2-18 months",

        earnings_channels=[
            "Revenue",
            "EBITDA",
            "EPS",
            "FCF",
        ],

        market_mistake=(
            "The market focuses on customer count and "
            "underestimates the incremental volume available "
            "from increasing usage by the existing customer base."
        ),

        second_order_effects=[
            "Higher customer lifetime value",
            "Improved retention",
            "Higher operating leverage",
            "Greater revenue visibility",
        ],

        disconfirming_evidence=[
            "Usage stagnation",
            "Lower consumption",
            "Falling transaction frequency",
            "Customer engagement deterioration",
        ],

        kill_switch=(
            "Existing customers fail to increase usage or "
            "consumption at the expected rate."
        ),
    ),


    # ======================================================
    # 4. REORDER / REPLACEMENT CYCLE ACCELERATION
    # ======================================================

    CatalystPattern(
        pattern_id="PAT-VOLUME-REORDER-CYCLE",
        family=CatalystFamily.VOLUME_GROWTH,
        name="Reorder / Replacement Cycle Acceleration",

        description=(
            "Customers replenish or replace products more "
            "frequently than previously expected, increasing "
            "unit demand and order frequency."
        ),

        trigger_signals=[
            "reorder acceleration",
            "replacement cycle shortening",
            "higher repeat orders",
            "faster replenishment",
            "replacement demand acceleration",
        ],

        mechanism=(
            "A shortening of the customer replacement or "
            "replenishment cycle causes existing customers "
            "to generate additional unit demand within a "
            "given period."
        ),

        transmission_channels=[
            "Order Frequency",
            "Unit Demand",
            "Shipments",
            "Revenue",
            "Working Capital",
        ],

        leading_indicators=[
            "Repeat order frequency",
            "Replacement intervals",
            "Replenishment rates",
            "Inventory depletion",
            "Customer reorder behaviour",
        ],

        confirmation_indicators=[
            "Higher repeat orders",
            "Shorter replacement intervals",
            "Higher shipment frequency",
            "Sustained replenishment growth",
        ],

        typical_time_horizon="3-24 months",

        earnings_channels=[
            "Revenue",
            "EBITDA",
            "EPS",
            "FCF",
        ],

        market_mistake=(
            "The market assumes historical replacement cycles "
            "will persist and fails to recognize an acceleration "
            "in replenishment or replacement demand."
        ),

        second_order_effects=[
            "Higher customer lifetime value",
            "Improved demand visibility",
            "Higher production utilisation",
            "Stronger channel throughput",
        ],

        disconfirming_evidence=[
            "Replacement cycle lengthening",
            "Lower reorder frequency",
            "Inventory accumulation",
            "Customer postponement",
        ],

        kill_switch=(
            "Customer replacement or replenishment frequency "
            "fails to improve or reverses toward historical levels."
        ),
    ),


    # ======================================================
    # 5. CHANNEL SELL-THROUGH ACCELERATION
    # ======================================================

    CatalystPattern(
        pattern_id="PAT-VOLUME-CHANNEL-SELL-THROUGH",
        family=CatalystFamily.VOLUME_GROWTH,
        name="Channel Sell-Through Acceleration",

        description=(
            "Existing distribution infrastructure begins "
            "moving materially higher unit volumes as end "
            "customer demand strengthens."
        ),

        trigger_signals=[
            "sell-through acceleration",
            "dealer offtake growth",
            "distributor throughput growth",
            "retail volume growth",
            "secondary sales acceleration",
        ],

        mechanism=(
            "Higher end-customer demand increases the number "
            "of units moving through existing dealers, "
            "distributors, retailers, or other channels."
        ),

        transmission_channels=[
            "Channel Throughput",
            "Units",
            "Inventory Conversion",
            "Shipments",
            "Revenue",
        ],

        leading_indicators=[
            "Dealer offtake",
            "Distributor secondary sales",
            "Retail traffic",
            "Channel inventory turns",
            "Point-of-sale volumes",
        ],

        confirmation_indicators=[
            "Higher sell-through",
            "Lower channel inventory",
            "Higher secondary sales",
            "Improved inventory turns",
            "Higher company shipments",
        ],

        typical_time_horizon="2-12 months",

        earnings_channels=[
            "Revenue",
            "EBITDA",
            "EPS",
            "FCF",
        ],

        market_mistake=(
            "The market focuses on primary shipments and "
            "fails to recognize improving underlying demand "
            "visible through channel sell-through."
        ),

        second_order_effects=[
            "Inventory replenishment",
            "Higher production volume",
            "Improved dealer economics",
            "Stronger future order flow",
        ],

        disconfirming_evidence=[
            "Channel inventory build",
            "Weak sell-through",
            "Dealer destocking",
            "Falling secondary sales",
        ],

        kill_switch=(
            "Improving primary shipments are not supported "
            "by genuine end-customer sell-through."
        ),
    ),


    # ======================================================
    # 6. HIGH-VOLUME PRODUCT SHIFT
    # ======================================================

    CatalystPattern(
        pattern_id="PAT-VOLUME-HIGH-VOLUME-PRODUCT-SHIFT",
        family=CatalystFamily.VOLUME_GROWTH,
        name="High-Volume Product Shift",

        description=(
            "Demand shifts toward products or SKUs that "
            "generate materially higher unit throughput, "
            "increasing aggregate physical volume."
        ),

        trigger_signals=[
            "high-volume SKU adoption",
            "unit mix shift",
            "faster-moving SKU growth",
            "standard product adoption",
            "higher-volume product demand",
        ],

        mechanism=(
            "A change in product-level demand causes a larger "
            "share of total activity to move toward products "
            "with higher unit throughput."
        ),

        transmission_channels=[
            "Unit Volume",
            "Product Throughput",
            "Production Mix",
            "Revenue",
            "Capacity Utilisation",
        ],

        leading_indicators=[
            "SKU-level unit trends",
            "Product-level orders",
            "Product sell-through",
            "SKU inventory turns",
            "Customer product preferences",
        ],

        confirmation_indicators=[
            "Higher unit contribution from target products",
            "Sustained SKU volume growth",
            "Higher aggregate unit throughput",
            "Improved production throughput",
        ],

        typical_time_horizon="3-18 months",

        earnings_channels=[
            "Revenue",
            "EBITDA",
            "EPS",
            "FCF",
        ],

        market_mistake=(
            "The market focuses on aggregate revenue or "
            "product-level economics and misses an important "
            "change in underlying unit demand."
        ),

        second_order_effects=[
            "Higher production efficiency",
            "Improved asset utilisation",
            "Procurement scale benefits",
            "Potential operating leverage",
        ],

        disconfirming_evidence=[
            "Target SKU demand deterioration",
            "Volume shift reversal",
            "Weak sell-through",
            "No aggregate unit increase",
        ],

        kill_switch=(
            "The product-level volume shift fails to produce "
            "a sustained increase in aggregate physical volume."
        ),
    ),
]


# ==========================================================
# PUBLIC API
# ==========================================================

__all__ = [
    "VOLUME_PATTERNS",
]