"""
EIOS
Everest Investment Operating System

Recovery Opportunity → Canonical Opportunity Signal Adapter

Purpose
-------
Converts a validated RecoveryOpportunitySignal into the
canonical Opportunity Intelligence Signal.

This adapter performs NO analytical calculation.

It does NOT:
- calculate valuation
- calculate mispricing
- calculate expectation gap
- rank opportunities
- make investment decisions

It only translates already-existing Recovery intelligence
into the canonical Opportunity Signal vocabulary.
"""

from copy import deepcopy

from modules.opportunity.signals.signal_model import (
    Signal,
    SignalDomain,
    SignalType,
    SignalDirection,
    SignalStage,
    TimeHorizon,
    EvidenceQuality,
)

from modules.opportunity.recovery.recovery_opportunity_signal import (
    RecoveryOpportunitySignal,
    RecoveryOpportunityDirection,
)


class RecoveryOpportunityAdapter:
    """
    Thin deterministic adapter between Recovery Intelligence
    and the canonical Opportunity Signal model.
    """

    # ======================================================
    # PUBLIC API
    # ======================================================

    @staticmethod
    def create_signal(
        recovery_signal: RecoveryOpportunitySignal,
    ) -> Signal:

        if recovery_signal is None:
            raise ValueError(
                "recovery_signal must not be None"
            )

        signal = Signal()

        # ==================================================
        # IDENTITY
        # ==================================================

        signal.signal_id = (
            f"RECOVERY::{recovery_signal.signal_id}"
        )

        signal.title = (
            recovery_signal.theme_name
            or "Recovery Opportunity Signal"
        )

        signal.description = (
            "Recovery opportunity signal generated "
            "from validated Recovery Intelligence."
        )

        # ==================================================
        # CLASSIFICATION
        # ==================================================

        signal.domain = (
            SignalDomain.SECTOR
        )

        signal.signal_type = (
            SignalType.INFLECTION
        )

        signal.direction = (
            RecoveryOpportunityAdapter._direction(
                recovery_signal
            )
        )

        signal.stage = (
            RecoveryOpportunityAdapter._stage(
                recovery_signal
            )
        )

        signal.horizon = (
            TimeHorizon.MEDIUM_TERM
        )

        # ==================================================
        # ENTITIES
        # ==================================================

        signal.sectors = []

        signal.companies = []

        signal.themes = [
            recovery_signal.theme_name
        ] if recovery_signal.theme_name else []

        # ==================================================
        # ECONOMIC MEANING
        # ==================================================

        signal.economic_mechanism = (
            "Recovery breadth, confirmation and "
            "catalyst evidence indicate a potential "
            "recovery regime."
        )

        signal.earnings_impact = (
            "Recovery intelligence may support future "
            "earnings improvement; no earnings forecast "
            "is generated by this adapter."
        )

        signal.valuation_impact = ""

        # ==================================================
        # SIGNAL STRENGTH
        # ==================================================

        signal.magnitude = (
            RecoveryOpportunityAdapter._bounded(
                recovery_signal.recovery_breadth
            )
        )

        signal.probability = (
            RecoveryOpportunityAdapter._bounded(
                recovery_signal.recovery_confidence
            )
        )

        signal.persistence = (
            RecoveryOpportunityAdapter._bounded(
                recovery_signal.persistence_score
            )
        )

        signal.relevance = (
            RecoveryOpportunityAdapter._bounded(
                recovery_signal.recovery_coherence
            )
        )

        signal.corroboration = (
            RecoveryOpportunityAdapter._bounded(
                recovery_signal.catalyst_coherence
            )
        )

        signal.confidence = (
            RecoveryOpportunityAdapter._bounded(
                recovery_signal.recovery_confidence
            )
        )

        signal.evidence_quality = (
            RecoveryOpportunityAdapter._evidence_quality(
                recovery_signal
            )
        )

        # ==================================================
        # EVIDENCE
        # ==================================================

        signal.evidence = list(
            recovery_signal.evidence_sources
        )

        signal.supporting_sources = list(
            recovery_signal.evidence_sources
        )

        signal.contradictory_evidence = list(
            recovery_signal.contradictory_evidence
        )

        # ==================================================
        # MARKET CONTEXT
        # ==================================================

        signal.market_expectation = ""

        signal.market_recognition = (
            RecoveryOpportunityAdapter._bounded(
                100.0
                - recovery_signal.recovery_confidence
            )
        )

        signal.price_reaction = ""

        # ==================================================
        # CAUSAL CHAIN
        # ==================================================

        signal.causal_chain = list(
            recovery_signal.catalyst_patterns
        )

        signal.beneficiaries = []

        signal.adversely_affected = []

        # ==================================================
        # VALIDATION
        # ==================================================

        signal.independent_confirmation = (
            recovery_signal.catalyst_count
        )

        signal.historical_precedent = ""

        signal.invalidation_conditions = [
            "Recovery breadth deteriorates materially.",
            "Confirmed recovery breadth fails to persist.",
            "Catalyst support weakens or disappears.",
        ]

        # ==================================================
        # METADATA
        # ==================================================

        signal.metadata = {
            "origin": "RECOVERY_INTELLIGENCE",
            "recovery_signal_id": (
                recovery_signal.signal_id
            ),
            "theme_id": (
                recovery_signal.theme_id
            ),
            "theme_name": (
                recovery_signal.theme_name
            ),
            "recovery_stage": (
                recovery_signal.stage.value
            ),
            "recovery_direction": (
                recovery_signal.direction.value
            ),
            "opportunity_ready": (
                recovery_signal.opportunity_ready
            ),
            "requires_more_evidence": (
                recovery_signal.requires_more_evidence
            ),
            "catalyst_families": list(
                recovery_signal.catalyst_families
            ),
            "catalyst_patterns": list(
                recovery_signal.catalyst_patterns
            ),
            "adapter_version": "1.0",
        }

        return signal

    # ======================================================
    # DIRECTION
    # ======================================================

    @staticmethod
    def _direction(
        recovery_signal,
    ) -> SignalDirection:

        if (
            recovery_signal.direction
            == RecoveryOpportunityDirection.POSITIVE
        ):
            return SignalDirection.POSITIVE

        if (
            recovery_signal.direction
            == RecoveryOpportunityDirection.NEGATIVE
        ):
            return SignalDirection.NEGATIVE

        if (
            recovery_signal.direction
            == RecoveryOpportunityDirection.NEUTRAL
        ):
            return SignalDirection.NEUTRAL

        return SignalDirection.UNKNOWN

    # ======================================================
    # STAGE
    # ======================================================

    @staticmethod
    def _stage(
        recovery_signal,
    ) -> SignalStage:

        stage = (
            recovery_signal.stage.value
            if recovery_signal.stage
            else ""
        )

        if stage == "Actionable":
            return SignalStage.CATALYST

        if stage == "Developing":
            return SignalStage.EMERGING

        if stage == "Watch":
            return SignalStage.WEAK

        return SignalStage.WEAK

    # ======================================================
    # EVIDENCE QUALITY
    # ======================================================

    @staticmethod
    def _evidence_quality(
        recovery_signal,
    ) -> EvidenceQuality:

        score = max(
            RecoveryOpportunityAdapter._bounded(
                recovery_signal.recovery_confidence
            ),
            RecoveryOpportunityAdapter._bounded(
                recovery_signal.catalyst_confidence
            ),
        )

        if score >= 90.0:
            return EvidenceQuality.A_PLUS

        if score >= 80.0:
            return EvidenceQuality.A

        if score >= 65.0:
            return EvidenceQuality.B

        if score >= 50.0:
            return EvidenceQuality.C

        if score >= 30.0:
            return EvidenceQuality.D

        return EvidenceQuality.D

    # ======================================================
    # BOUNDS
    # ======================================================

    @staticmethod
    def _bounded(
        value,
    ) -> float:

        try:
            value = float(value)
        except (
            TypeError,
            ValueError,
        ):
            return 0.0

        return max(
            0.0,
            min(
                100.0,
                value,
            ),
        )


__all__ = [
    "RecoveryOpportunityAdapter",
]