"""
EIOS
Everest Investment Operating System

Institutional Intrinsic Value Office

Architecture

Valuation Office
        ↓
Intrinsic Value Office
        ↓
Intrinsic Value Engine
        ↓
IntrinsicValueResult

The Office performs orchestration only.

No valuation calculations occur here.
"""

from modules.valuation.intrinsic_value_engine import (
    IntrinsicValueEngine,
)

from modules.valuation.intrinsic_value_models import (
    IntrinsicValueResult,
)


class IntrinsicValueOffice:
    """
    Institutional Intrinsic Value Office.

    Coordinates intrinsic value estimation by delegating
    all calculations to the Intrinsic Value Engine.
    """

    OFFICE_NAME = "Intrinsic Value Office"

    def __init__(self):

        self.engine = IntrinsicValueEngine()

    def evaluate(
        self,
        valuation_summary: dict,
    ) -> IntrinsicValueResult:

        result = self.engine.evaluate(
            valuation_summary
        )

        return IntrinsicValueResult(

            fair_value=result["Fair Value"],

            low_estimate=result["Low Estimate"],

            high_estimate=result["High Estimate"],

            confidence=result["Confidence"],

            agreement=result["Method Agreement"],

            primary_method=result["Primary Method"],

            supporting_methods=result[
                "Supporting Methods"
            ],

            valuation_count=len(
                result["Supporting Methods"]
            ),

            spread_percent=round(
                (
                    (
                        result["High Estimate"]
                        - result["Low Estimate"]
                    )
                    / result["High Estimate"]
                )
                * 100,
                2,
            )
            if result["High Estimate"] > 0
            else 0,

            summary=(
                "Institutional intrinsic value "
                "generated by the Intrinsic "
                "Value Office."
            ),
        )